name: RoseBay
favicon: null
layout_spectrum: 0.36867
typography_spectrum: 0.19428
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 1
  lightness: 0.7520860931836069
  saturation: 0.125
  rhythmicContrast: 0.25
purpose: []
